#ifndef LIBIRCCLIENT_PARAMS_H
#define LIBIRCCLIENT_PARAMS_H
#ifndef IN_LIBIRCCLIENT_H
	#error This file should not be included directly; include just libircclient.h
#endif
#define LIBIRCCLIENT_BUFFER_SIZE		1024
#define LIBIRCCLINET_STATE_INIT		0
#define LIBIRCCLIENT_STATE_CONNECTING	2
#define LIBIRCCLIENT_STATE_CONNECTED	3
#define LIBIRCCLIENT_STATE_DISCONNECTED	4
#endif /* LIBIRCCLIENT_PARAMS_H */
